# Generated by Django 5.0.2 on 2024-03-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
